sudo: required

language: python
python:
  - "3.7"

arch:
  - amd64

os:
  - linux

addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
      - xvfb
      - herbstluftwm # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events
      - qt5-default
      - qttools5-dev-tools

# enable virtual framebuffer for testing GUI
services:
  - xvfb


env:
  - DISPLAY=":99.0" QT_DEBUG_PLUGINS=1 PYTHONASYNCIODEBUG=1  # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html?highlight=travis#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events

install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U pylint
  - pip install -U coveralls
  - pip install -U pytest-qt
  - pip install -e .
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3

# make directories?
before_script:
  - "herbstluftwm &"
  - sleep 1
  - mkdir -p /home/travis/autopilot # make directories for logs
  # - pylint autopilot

script:
  - pytest --cov=autopilot --cov-config=.coveragerc --cov-report term-missing tests

after_script:
  - coverage combine --append
  - coveralls

before_deploy:
  - pip install scikit-build

deploy:
  provider: pypi
  username: __token__
  pasword:
    secure: mIaKgOMl4tjUvLlpSGwbuUj2A7QK0nMnQzlYygdVN5vCuvXnggScytqwXNqjSqjB3cn0R4EKllCfnREsIqBgYrEsRCRIexwLuz58KDo6qjSad/ycpCjmtz/6nvuJp3I2iJGudzCZ/W1MCpz0ExAvvHXm7k0U4J831bK+mFYqe8RHJxcAuYMJndEUaD5s/Ly+ozqJYx3H9+f/fggpVAlGu/oy5p77so9vQA0xvayodQKzL1XGvNHBXMEKtBtEN33pTKDbOY3bQ7GR0WLE7pd+bg1rZ/r5EsvlHAlHR/rSCWDNq4K0Qk3ZyUeHLX9UjKIImXbhMMyNSyz98DkgUd/TkfGG2K2jyKd7WR1KqOrNjy+clqTdyj1fcHtm8au6YsvYLvR9qmO1prwrGq1vMH0/qvOrcM3+OU3hGdUwtjth3F+TTsc57O22qHjpeq/xlWtFC8vAF92ZHzPWW6xBApYB3+MJZHh27LJL/rdbAv/WoYPZbQWiqxNm869GCaSzjBGZ/Zx5BPpGbJUb8N+pBHgow3gww2TMS1C7W3gDVPm42DL8ehhOEJZBT9FIfzAooeyxzyvUb6gSdtshGUuJPe8HdZhNn5n4rFuSoZ7edCbEEM7bQ/gqOJK9Ccr+4yi/9MHBXB7LsjB32tzlxbsEePG18ac85wJp1Z64QYMpzV5DAi0=
  on:
    tags: true
    branch: master
  distributions: "sdist"

